### ISSUE TITLE
"Access point name"

### ISSUE THREAD

**Issue by luckman212** [mikaellofgren/wandra#1]
Hi & thank you for sharing this very unique and useful utility!

I was wondering what the purpose of the _"Access point name"_ field is? Are we supposed to type something here to track roaming between APs? The value does not appear to save anywhere.

<img width=200 src=https://user-images.githubusercontent.com/1992842/159961654-c4dc8967-06be-4462-87a4-db0090dcdfd1.png>

**Comment by mikaellofgren** [comment]
Hi!
Yes, you should be able to type in the matching name of the AP (like Floor 2), but I recommend to set the measure interval to something higher, then type name followed by Return.

Then if you wanna save all the measured data, right click the Pause/Play button and you should see the AP name as a field in saved file.

**Comment by mikaellofgren** [comment]
And it also should be displayed as a help text is you hover over that field! =)

**Comment by luckman212** [comment]
Ah yes I see the tooltip now, I didn't think about hovering. Thanks! 🙏 

In case you're open to any suggestions, it would be very nice if the custom names were saved in the app's preference plist, so it persisted across launches.

**Comment by mikaellofgren** [comment]
Nice it worked!
Yes I will think about a preferences, but the whole app is "preference" free.
I close this case and keep that I mind, thanks!

**Comment by luckman212** [comment]
@mikaellofgren I used Wandra today to test roaming between 18 APs we set up in a new office. It was really helpful! Thanks 🙏🏻 again.
